# Generated by Django 5.2.6 on 2025-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mastertrainercertificate_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainersubmission',
            name='rejection_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rejection Authority'),
        ),
    ]
