# Generated by Django 5.2.6 on 2025-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mastertrainersubmission_rejection_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainercertificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reverted', 'Reverted')], db_index=True, default='pending', max_length=16),
        ),
    ]
