# Generated by Django 5.2.6 on 2025-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mastertrainercertificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertrainer',
            name='designation',
            field=models.CharField(blank=True, choices=[('DRP', 'DRP'), ('SRP', 'SRP')], db_index=True, max_length=3, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='mastertrainersubmission',
            name='designation',
            field=models.CharField(blank=True, choices=[('DRP', 'DRP'), ('SRP', 'SRP')], db_index=True, max_length=3, null=True, verbose_name='Designation'),
        ),
        migrations.AddIndex(
            model_name='mastertrainer',
            index=models.Index(fields=['designation'], name='main_master_designa_639a58_idx'),
        ),
        migrations.AddIndex(
            model_name='mastertrainersubmission',
            index=models.Index(fields=['designation'], name='main_master_designa_b3a53d_idx'),
        ),
    ]
