# Generated by Django 5.2.6 on 2025-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mastertrainer_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='empanel_district',
            field=models.CharField(blank=True, choices=[('Agra', 'Agra'), ('Aligarh', 'Aligarh'), ('Allahabad (Prayagraj)', 'Allahabad (Prayagraj)'), ('Ambedkar Nagar', 'Ambedkar Nagar'), ('Amethi', 'Amethi'), ('Amroha', 'Amroha'), ('Auraiya', 'Auraiya'), ('Azamgarh', 'Azamgarh'), ('Baghpat', 'Baghpat'), ('Bahraich', 'Bahraich'), ('Ballia', 'Ballia'), ('Balrampur', 'Balrampur'), ('Banda', 'Banda'), ('Barabanki', 'Barabanki'), ('Bareilly', 'Bareilly'), ('Basti', 'Basti'), ('Bhadohi (Sant Ravidas Nagar)', 'Bhadohi (Sant Ravidas Nagar)'), ('Bijnor', 'Bijnor'), ('Budaun', 'Budaun'), ('Bulandshahr', 'Bulandshahr'), ('Chandauli', 'Chandauli'), ('Chitrakoot', 'Chitrakoot'), ('Deoria', 'Deoria'), ('Etah', 'Etah'), ('Etawah', 'Etawah'), ('Faizabad (Ayodhya)', 'Faizabad (Ayodhya)'), ('Farrukhabad', 'Farrukhabad'), ('Fatehpur', 'Fatehpur'), ('Firozabad', 'Firozabad'), ('Gautam Buddha Nagar (Noida)', 'Gautam Buddha Nagar (Noida)'), ('Ghaziabad', 'Ghaziabad'), ('Ghazipur', 'Ghazipur'), ('Gonda', 'Gonda'), ('Gorakhpur', 'Gorakhpur'), ('Hamirpur', 'Hamirpur'), ('Hapur', 'Hapur'), ('Hardoi', 'Hardoi'), ('Hathras', 'Hathras'), ('Jalaun', 'Jalaun'), ('Jaunpur', 'Jaunpur'), ('Jhansi', 'Jhansi'), ('Kannauj', 'Kannauj'), ('Kanpur Dehat', 'Kanpur Dehat'), ('Kanpur Nagar', 'Kanpur Nagar'), ('Kasganj', 'Kasganj'), ('Kaushambi', 'Kaushambi'), ('Kushinagar', 'Kushinagar'), ('Lakhimpur Kheri', 'Lakhimpur Kheri'), ('Lalitpur', 'Lalitpur'), ('Lucknow', 'Lucknow'), ('Maharajganj', 'Maharajganj'), ('Mahoba', 'Mahoba'), ('Mainpuri', 'Mainpuri'), ('Mathura', 'Mathura'), ('Mau', 'Mau'), ('Meerut', 'Meerut'), ('Mirzapur', 'Mirzapur'), ('Moradabad', 'Moradabad'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Pilibhit', 'Pilibhit'), ('Pratapgarh', 'Pratapgarh'), ('Rae Bareli', 'Rae Bareli'), ('Rampur', 'Rampur'), ('Saharanpur', 'Saharanpur'), ('Sant Kabir Nagar', 'Sant Kabir Nagar'), ('Sant Ravidas Nagar', 'Sant Ravidas Nagar'), ('Shahjahanpur', 'Shahjahanpur'), ('Shamli', 'Shamli'), ('Shravasti', 'Shravasti'), ('Siddharthnagar', 'Siddharthnagar'), ('Sitapur', 'Sitapur'), ('Sonbhadra', 'Sonbhadra'), ('Sultanpur', 'Sultanpur'), ('Unnao', 'Unnao'), ('Varanasi', 'Varanasi')], max_length=255, null=True, verbose_name='Empanel District'),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced/Widowed', 'Divorced/Widowed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='social_category',
            field=models.CharField(blank=True, choices=[('General - UR', 'General/Unreserved'), ('SC', 'Scheduled Castes'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class')], max_length=50, null=True, verbose_name='Social Category'),
        ),
    ]
