# Generated by Django 5.2.6 on 2025-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mastertrainersubmission_empanel_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='education',
            field=models.CharField(blank=True, choices=[('Under Graduate (UG)', 'Under Graduate (UG)'), ('Post Graduate (PG)', 'Post Graduate (PG)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='social_category',
            field=models.CharField(blank=True, choices=[('UR', 'General/Unreserved (UR)'), ('SC', 'Scheduled Castes (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('OBC', 'Other Backward Class (OBC)')], max_length=50, null=True, verbose_name='Social Category'),
        ),
        migrations.AlterField(
            model_name='mastertrainersubmission',
            name='education',
            field=models.CharField(blank=True, choices=[('Under Graduate (UG)', 'Under Graduate (UG)'), ('Post Graduate (PG)', 'Post Graduate (PG)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainersubmission',
            name='social_category',
            field=models.CharField(blank=True, choices=[('UR', 'General/Unreserved (UR)'), ('SC', 'Scheduled Castes (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('OBC', 'Other Backward Class (OBC)')], max_length=50, null=True, verbose_name='Social Category'),
        ),
    ]
