# Generated by Django 5.2.6 on 2025-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mastertrainer_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertrainer',
            name='education',
            field=models.CharField(blank=True, choices=[('Literate', 'Literate'), ('8th Pass', '8th Pass'), ('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Under Graduate (UG)', 'Under Graduate (UG)'), ('Post Graduate (PG)', 'Post Graduate (PG)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mastertrainer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20, null=True),
        ),
    ]
